version: "3"
services:
  node:
    build:
      context: .
      dockerfile: caliper-besu-clique.Dockerfile
    image: caliper-besu-clique
    container_name: besu_clique
    volumes:
      - ./keys:/root/.ethereum/keystore
    ports:
      - 8545-8547:8545-8547
    command: --revert-reason-enabled --rpc-http-enabled --rpc-http-host 0.0.0.0 --host-whitelist=* --rpc-http-apis admin,eth,miner,web3,net --graphql-http-enabled --discovery-enabled=false
